name: Front CI

on:
  push:
    branches: [ main ]
    tags:
      - 'v*'
  pull_request:
    branches: [ main ]
    
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 16
      - name: Install dependencies
        run: npm install 
      - name: Build app
        run: CI=false npm run build 
      - name: testls 
        run: ls 
      - name: Arch build
        run: tar -czvf build.tar.gz ./build
      - name: test
        run: echo $GITHUB_REF_NAME
  release:
    if: startsWith(github.ref, 'refs/tags/v')
    needs: [build]
    runs-on: ubuntu-latest
    steps:
    - name: Get build
      uses: actions/download-artifact@master
      with:
        name: build.tar.gz
        path: .
    - name: Save
      uses: softprops/action-gh-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        files: |
          build.tar.gz
